server:
  port: 8019

spring:
  config:
    import:
      - optional:file:./config/application-global.properties
      - optional:file:../config/application-global.properties
  application:
    name: SAA-19GaodeRag

  ai:
    dashscope:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus
    weather:
      amap:

logging:
  level:
    com.atguigu.study: DEBUG
    org.springframework.ai: INFO

